/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    GameCard: typeof import('./src/components/GameCard.vue')['default']
    GameCardSkeleton: typeof import('./src/components/Cards/GameCardSkeleton.vue')['default']
    GameList: typeof import('./src/components/GameList.vue')['default']
    MainWrapper: typeof import('./src/components/MainWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastError: typeof import('./src/components/ToastError.vue')['default']
  }
}
